# Generated by Django 4.0.4 on 2022-05-04 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='favoriteitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='FavoriteItem',
        ),
    ]
